runtime: php74
service: php-gcp

#entrypoint: serve index.php
entrypoint: serve services/php_gcp/simpleform.php

handlers:
  - url: /
    script: auto

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  max_pending_latency: 2000ms